"""initial_schema_v2

Revision ID: 827540644ebb
Revises: None
Create Date: 2026-05-07 19:09:28.776484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827540644ebb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_index(op.f('ix_levels_level_id'), 'levels', ['level_id'], unique=False)
    op.create_table('provinces',
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('province_id')
    )
    op.create_index(op.f('ix_provinces_province_id'), 'provinces', ['province_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_units_unit_id'), 'units', ['unit_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_metrics_metric_id'), 'metrics', ['metric_id'], unique=False)
    op.create_table('stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('idema', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.province_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_stations_idema'), 'stations', ['idema'], unique=True)
    op.create_index(op.f('ix_stations_station_id'), 'stations', ['station_id'], unique=False)
    op.create_table('thresholds',
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.level_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.create_index(op.f('ix_thresholds_threshold_id'), 'thresholds', ['threshold_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('threshold_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.metric_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threshold_id'], ['thresholds.threshold_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_records_record_id'), 'records', ['record_id'], unique=False)
    op.create_index(op.f('ix_records_timestamp'), 'records', ['timestamp'], unique=False)
    op.create_table('records_alerts',
    sa.Column('record_alert_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['records.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_alert_id')
    )
    op.create_index(op.f('ix_records_alerts_record_alert_id'), 'records_alerts', ['record_alert_id'], unique=False)
    op.create_table('sent_alerts',
    sa.Column('sent_alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sent_alert_id')
    )
    op.create_index(op.f('ix_sent_alerts_sent_alert_id'), 'sent_alerts', ['sent_alert_id'], unique=False)
    op.create_index(op.f('ix_sent_alerts_sent_at'), 'sent_alerts', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_alerts_sent_at'), table_name='sent_alerts')
    op.drop_index(op.f('ix_sent_alerts_sent_alert_id'), table_name='sent_alerts')
    op.drop_table('sent_alerts')
    op.drop_index(op.f('ix_records_alerts_record_alert_id'), table_name='records_alerts')
    op.drop_table('records_alerts')
    op.drop_index(op.f('ix_records_timestamp'), table_name='records')
    op.drop_index(op.f('ix_records_record_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_thresholds_threshold_id'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index(op.f('ix_stations_station_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_idema'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_metrics_metric_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_unit_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_provinces_province_id'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_levels_level_id'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###