"""add telegram sync token

Revision ID: 36c9f5b3887a
Revises: 9359c7d7fb55
Create Date: 2026-05-14 12:50:36.521500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '36c9f5b3887a'
down_revision: Union[str, None] = '9359c7d7fb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###